### ISSUE TITLE
Floating box (footnote, citation) is trimmed by page limits

### ISSUE THREAD

**Issue by rnsanchez** [thomaspark/pubcss#9]
If the citation/footnote is too close to the margin, the floating box gets trimmed like shown below.  This was captured on Google's Chrome Version 54.0.2840.71 (64-bit) for Linux.

From: http://thomaspark.co/project/pubcss/demo/acm-sig-sample-web-theme.html

![footnote](https://cloud.githubusercontent.com/assets/87608/21009914/52192d78-bd30-11e6-8711-dc4094f4ac46.png)

**Comment by thomaspark** [comment]
Thanks for the heads up. It seems to be a Chrome bug with rendering elements that overflow on body, since it displays fine on Firefox and Safari. But I've added a workaround so it should look nice in Chrome now.

<img width="913" alt="screen shot 2016-12-08 at 2 02 36 pm" src="https://cloud.githubusercontent.com/assets/900407/21023590/26dcc434-bd4f-11e6-877c-f67588a48872.png">

**Comment by rnsanchez** [comment]
That was quick!  Thank you!  :-)

Fix confirmed.
